import { Processor, WorkerHost } from "@nestjs/bullmq";
import { Job } from "bullmq";
import { OctokitService } from "src/github/octokit.service";
import { GoogleGenAI } from "@google/genai";

@Processor('pr-review-queue')
export class PrReviewProcessor extends WorkerHost {
    private gemini: GoogleGenAI;

    constructor(private readonly octokitService: OctokitService) {
        super();

        // Initialize Google Gemini AI client
        this.gemini = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });
    }

    async process(job: Job): Promise<any> {
        const { repo, prNumber, installationId } = job.data;
        const octokit = await this.octokitService.getInstallationClient(installationId);
        const [owner, repoName] = repo.split('/');

        // Fetch the PR Diff
        const { data: diff } = await octokit.rest.pulls.get({
            owner,
            repo: repoName,
            pull_number: prNumber,
            mediaType: {
                format: 'diff',
            },
        }) as unknown as { data: string };

        // Parallel AI Review
        const [architectReview, securityReview] = await Promise.all([
            this.getGeminiArchitectReview(diff),
            this.getGrokSecurityReview(diff)
        ]);

        // Final Formatted Comment
        const finalComment = `
            ## 🛡️ Sentinel Architect Report

            ### Architectural Insights (Gemini)
            ${architectReview}

            ---

            ### Security Audit (Grok)
            ${securityReview}

            ---
            *Generated by Sentinel Architect v1.0.0*
        `;

        // Post back to GitHub
        await octokit.rest.issues.createComment({
            owner,
            repo: repoName,
            issue_number: prNumber,
            body: finalComment,
        });

        return { status: 'success' };
    }

    private async getGeminiArchitectReview(diff: string) {
        const response = await this.gemini.models.generateContent({
            model: 'gemini-2.0-flash',
            contents: [{ role: 'user', parts: [{ text: `Review this PR diff for architectural flaws:\n${diff}` }] }],
            config: {
                systemInstruction: 'You are a Senior Architect. Focus on clean code, SOLID principles, and design patterns.',
                temperature: 0.1,
            },
        });
        return response.text;
    }

    private async getGrokSecurityReview(diff: string) {
        const response = await fetch('https://api.x.ai/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${process.env.GROK_API_KEY}`
            },
            body: JSON.stringify({
                "messages": [
                    { role: 'system', content: 'You are a Security Researcher. Hunt for SQLi, XSS, and hardcoded secrets.' },
                    { role: 'user', content: `Audit this diff:\n${diff}` }
                ],
                "model": "grok-4-latest",
                "stream": false,
                "temperature": 0.2
            })
        });
        const data = await response.json();
        return data.choices[0].message.content;
    }
}